### ISSUE TITLE
Type information

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/Scale#1]
What I want is

```
let time = 5.hour + 2.minute
```

`time` must be displayed with `Time<Minute>` or `Time.Minute`, now it is just `Time`

**Comment by ntnhon** [comment]
Agreed.

Ideally we expect something with more context and more readable like:

`let time: Time.minute = 5.hour + 2.minute + 10.second`

**Comment by onmyway133** [comment]
@ntnhon oh right. In the mean time, you can take a look at https://github.com/onmyway133/Scale/issues/4
